### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by provsalt** [Heisenburger69/BurgerSpawners#1]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & BurgerSpawners
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

When you try and break a spawner,it wouldn't let me break as the ui popped up.
#### **Version:**
- BurgerSpawners: 0.0.1

- PMMP: 3.9.4

- OS: Linux

#### **Steps to Reproduce the Issue**

1. Install the plugin
2. Place a monster spawner from /spawner
3. try to break it.

#### **Extra Information**
N/A
As well add silktouched spawners and add more entities.

**Comment by Heisenburger69** [comment]
Fixed in [Latest Commit](https://github.com/Heisenburger69/BurgerSpawners/commit/308a39a02a6dbc9843aff2a94d257b94ea79663d)
Spawners already get picked up by pickaxes with silk touch
