### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MrHuskyy** [Heisenburger69/BurgerSpawners#10]
Can u make : ,,BurgerSpawners" - configurable? Like i want to rename it to some name also , when i type /spawner = BurgerSpawners -.
I want to rename it.

**Comment by provsalt** [comment]
No so its harder for noobs to claim the plugins as theirs

**Comment by MrHuskyy** [comment]
Idc, what u say. I give a suggestion.

**Comment by provsalt** [comment]
> Idc, what u say. I give a suggestion.

wait for your suggestion to be denied then "idc"

**Comment by Heisenburger69** [comment]
Prov is right, there's an issue with resellers in the community, so this is a small minimal thing that can be used to somewhat stop that from happening
