### ISSUE TITLE
I get this error when a player joines

### ISSUE THREAD

**Issue by MrNinja008** [Heisenburger69/BurgerSpawners#104]
Error: Call to undefined method pocketmine\item\Sword::write()
File: pmsrc/src/pocketmine/network/mcpe/protocol/MobEquipmentPacket
Line: 55
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.7.0

Code:
[46] 		$this->entityRuntimeId = $this->getEntityRuntimeId();
[47] 		$this->item = ItemStackWrapper::read($this);
[48] 		$this->inventorySlot = (\ord($this->get(1)));
[49] 		$this->hotbarSlot = (\ord($this->get(1)));
[50] 		$this->windowId = (\ord($this->get(1)));
[51] 	}
[52] 
[53] 	protected function encodePayload(){
[54] 		$this->putEntityRuntimeId($this->entityRuntimeId);
[55] 		$this->item->write($this);
[56] 		($this->buffer .= \chr($this->inventorySlot));
[57] 		($this->buffer .= \chr($this->hotbarSlot));
[58] 		($this->buffer .= \chr($this->windowId));
[59] 	}
[60] 
[61] 	public function handle(NetworkSession $session) : bool{
[62] 		return $session->handleMobEquipment($this);
[63] 	}
[64] }
Backtrace:
#0 pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\MobEquipmentPacket->encodePayload()
#1 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(244): pocketmine\network\mcpe\protocol\DataPacket->encode()
#2 pmsrc/src/pocketmine/Player(3359): pocketmine\network\mcpe\RakLibInterface->putPacket(object pocketmine\Player, object pocketmine\network\mcpe\protocol\MobEquipmentPacket, boolean , boolean )
#3 pmsrc/src/pocketmine/Player(3376): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\MobEquipmentPacket, boolean , boolean )
#4 plugins/PureEntitiesX (6).phar/src/revivalpmmp/pureentities/entity/monster/walking/WitherSkeleton(72): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\MobEquipmentPacket)
#5 pmsrc/src/pocketmine/entity/Entity(1971): revivalpmmp\pureentities\entity\monster\walking\WitherSkeleton->spawnTo(object pocketmine\Player)
#6 plugins/BurgerSpawners (2).phar/src/Heisenburger69/BurgerSpawners/Tiles/MobSpawnerTile(101): pocketmine\entity\Entity->spawnToAll()
#7 pmsrc/src/pocketmine/level/Level(868): Heisenburger69\BurgerSpawners\Tiles\MobSpawnerTile->onUpdate()
#8 pmsrc/src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 534)
#9 pmsrc/src/pocketmine/Server(2265): pocketmine\level\Level->doTick(integer 534)
#10 pmsrc/src/pocketmine/Server(2396): pocketmine\Server->checkTickUpdates(integer 534, double 1621760829.173)
#11 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#12 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#13 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
#14 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#15 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
#16 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Lentou** [comment]
the plugin was cause by PureEntitiesX, not the spawners
