### ISSUE TITLE
plugin don't work :/

### ISSUE THREAD

**Issue by Sulfuritium** [Heisenburger69/BurgerSpawners#110]
Hello, the plugin does not load after dev 100 :

Plugins (76): AddNetherite-HiroTeam v2.0.0, AdminLogin v1.0.0, AfkKick v1.1, Annonce v1.0.0, AntiVoid v1.1.0, AnvilUI v0.1, ArmorEffect-Patched_By_GamingFR91 v1.0.0, AuctionHouseUI v1.0.1, AutoClearLagg v3.0.0, AutoInv v0.0.10, BPSignShop v1, BetterVoting v2.0.2, BlazinFly v1.8.7, BlockItemFrame v2.0.0, BlockSniper v3.2.3, BuilderTools v1.2.0-beta2, CBreaker v1.0.0, ChestShop v2.4.0, CombatLogger v0.0.6, CustomAlerts v2.1, CustomArmor v1.0.0, CustomCraftPlus virvolta_0.3, DevTools v1.14.1, EC-TableUI v1.1.1-pre, EasyKits v1.1.5, EconomyAPI v5.7.3, Elevator v1.2, EnderpearlCooldown v1, FarmingChest v1.0.0, FirstJoinUI v1.2.0, FormAPI v1.3.0, Furnace v0.0.1, InvCrashFix v0.0.1, InvSee v1.0.0, LoadAllWorlds v1.1.2, LuckyBlock v1, MCPEDiscordRelay v1.0.9, MOTDShuffle v1.1.7, MSpawns v2.2, Minion v1.9.5, NameSpaceRemover v1.0.0, NoFallDamage v1.0, NoTP v1.0.7, OnlineATM v1.0.0, OnlineTime v1.3, OreGen v1.2.5, PiggyCrates v2.0.9, PiggyCustomEnchants v2.4.1, PlayerInfo v2.1.3, PlayerSelectors v1.0.0, PnjTrade v1.0.0, PocketLotto v1.1.1, ProtectArmor v1.0.0, PureChat v1.4.11, PurePerms v1.4.2, RedstoneCircuit v2.0.0, ScoreHud v5.2.0, Server_Name v1, ShopUI v1.0.0, SkyBlock v3.0.0, Slapper v1.6.1, SlapperRotation v1.2.1, Spy v1.0.0, SulfuCapes v2.0.3, SulfuDrops v1.0.0, SulfuFeed v1.0.2, Sword2 v1, TPA v0.0.1, Tebex v0.0.1, VMMPE-Action v1.0.0-BETA, VanishV2 v1.20, Warp v1, WorldGuard v1.1.93, Worlds v3.0.6, iProtector v3.1.1, xyz v1.0.8

![image](https://user-images.githubusercontent.com/74468167/125208853-504a8e80-e295-11eb-9f41-f5035691234f.png)

**Comment by Heisenburger69** [comment]
If there is an error in the console while the server is starting, paste it here

**Comment by Sulfuritium** [comment]
There is no error in the console, it just doesn't load

**Comment by Heisenburger69** [comment]
Issue on your end then, works fine for me
