### ISSUE TITLE
Hello, owner! Pls update to this to 1.17.30 also 3.23.1 plzz

### ISSUE THREAD

**Issue by FachriPlayz** [Heisenburger69/BurgerSpawners#119]

**Comment by FachriPlayz** [comment]
Pls update to 1.17.30 and also 3.23.1

**Comment by FachriPlayz** [comment]
When burgerspawner gonna update this to 1.17.30???

**Comment by suerion** [comment]
Spamming in all Plugin Github does not let the plugins update it! Ithink, you should use an server anymore
