### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Centoller** [Heisenburger69/BurgerSpawners#13]
sometimes the spawner level drops back to 1, how do I fix it? also does not let me put bees or foxes to the spawner

**Comment by iZeaoGamer** [comment]
I can confirm this is an issue above. It only happens upon every restart. Not sure if this was intentional or not.

**Comment by Centoller** [comment]
I have version 0.0.4

**Comment by Centoller** [comment]
the bees and foxes already appeared to me, but the levels of the Spawners continue to disappear when leaving the world

**Comment by Heisenburger69** [comment]
Fixed in latest commit, ty @Unickorn
