### ISSUE TITLE
Spawner stack resetting issue

### ISSUE THREAD

**Issue by iZeaoGamer** [Heisenburger69/BurgerSpawners#16]
Now, I believe most of you are aware of this issue.
Yes, spawner stacks do reset on every server restart, or everytime you leave, and rejoin.
This has previously been addressed. I can’t speak for the developers of this project, but I can say they’re working their butts off to make this plugin a success. I’m sure they’ll plan on fixing those bugs very soon.

## What’s causing this bug to happen?
I’m not sure at this point. We’d have to go by every plugin to see if it causes the issue from their side. If not, then we can reproduce their code to this one, which should allow them to see what’s wrong and why the issue is occurring. Again, this is still unconfirmed as of posting this.

## Any ETA’s as to when it will be fixed?
Again, I can’t speak for the developers, so I have no clue as to why, how, and when this issue will be reproduced, and fixed. At the moment, it’s a waiting game.

## Any notes to add?
Not at the moment. Except, as always, stick to the latest plugin release on the poggit releases page.
Dev builds are bleeding edge builds, so as stated from many of the websites, dev builds could harm your server. No, I’m not discouraging you to download dev builds. I’m simply saying to check the code before downloading. Anything could occurr, or happen if you don’t read the code.

Enjoy.

**Comment by NidPlays** [comment]
can confirm

**Comment by Heisenburger69** [comment]
Fixed in latest commit, ty @Unickorn
