### ISSUE TITLE
No Mob Spawning

### ISSUE THREAD

**Issue by MonoAdrian23** [Heisenburger69/BurgerSpawners#21]
Since Pocketmine 3.11.5 no Mob Spawning 
I use the latest Version of Burger Spawners
Its the best Plugin and i hope you can help me.
I have nothing changed.
Sorry for my bad english.

**Comment by iZeaoGamer** [comment]
No one can reproduce this. It all works fine for me, and I’m using the same version as you.

**Comment by provsalt** [comment]
Reproduced this.It was burgerspawner 0.0.5.Downgrade to 0.0.4 for now

**Comment by Heisenburger69** [comment]
@provsalt Was this tested on a clean server?

**Comment by provsalt** [comment]
> @provsalt Was this tested on a clean server?

I will test on a clean server rn.

**Comment by provsalt** [comment]
Tested waited around 3 minutes still no mobs spawned.

**Comment by Heisenburger69** [comment]
Alright, I'll investigate, if you have an idea what the issue could be, feel free to PR/tell me what you think it is

**Comment by Heisenburger69** [comment]
@iZeaoGamer This might be due to changes in how Spawner Load range was made configurable in your PR, have any ideas?

**Comment by Heisenburger69** [comment]
Update: It was. 
Adding a line "spawn-range: 8" in the config fixes the issue. Not sure how I could fix this other than make it set a default value if the config entry isn't found

**Comment by provsalt** [comment]
> Update: It was.
> Adding a line "spawn-range: 8" in the config fixes the issue. Not sure how I could fix this other than make it set a default value if the config entry isn't found

I might be able to pr you a configupdater using jacks virion to notify people to update their config next time to prevent this from happening again.

**Comment by Heisenburger69** [comment]
Sounds good to me, please do!

**Comment by ZZWILLIAMXXTrue** [comment]
Not having this issue, using 0.0.5 too.

**Comment by Heisenburger69** [comment]
Issue resolved(to an extent) in latest build
