### ISSUE TITLE
Disable in worlds [Suggestion]

### ISSUE THREAD

**Issue by Johnsonk79** [Heisenburger69/BurgerSpawners#22]
Hello, I suggest that you can disable the plugin in certain worlds because currently, every single mob in the server will stack and not attack player, makes it impossible for things such as normal survival or mob arena, it will be great if you can choose to disable mobs stacking or spawners in some worlds

**Comment by Heisenburger69** [comment]
I'll add in an option to disable stacking in certain worlds in the next release

**Comment by Heisenburger69** [comment]
Added in latest build

**Comment by Johnsonk79** [comment]
thx!
