### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by provsalt** [Heisenburger69/BurgerSpawners#27]
An API like giving spawners etc.

**Comment by iZeaoGamer** [comment]
That's a good idea, I guess if this was added, then other developers could play around with this.

**Comment by provsalt** [comment]
> That's a good idea, I guess if this was added, then other developers could play around with this.

Yeah I am  thinking of making a shop plugin with an API rather then implementing the same function or dispatching a command via ConsoleCommandSender.

**Comment by iZeaoGamer** [comment]
> > That's a good idea, I guess if this was added, then other developers could play around with this.
> 
> Yeah I am thinking of making a shop plugin with an API rather then implementing the same function or dispatching a command via ConsoleCommandSender.

Yeah, that seems like a perfect idea.

**Comment by Heisenburger69** [comment]
Basic API added in latest commit, not sure if you need any more methods
