### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by Dapro718** [Heisenburger69/BurgerSpawners#29]
I want to start this issue by saying, this is a awesome plugin and I am very thankful you have taken the time to create it. I also understand that you are probable being spammed with issues, so this issue isn’t that high on priority’s.

Issue:
Vanilla enchants don’t work on mobs. For example, if you have sharpness on a sword the sword still does the base damage rate.

Suggestion: 
When and if you fix this bug, maybe consider adding Custom Enchants (DaPigGuy) support.

**Comment by Johnsonk79** [comment]
I don't think the problem is caused by this plugin, you need a vanilla enchantment plugin to make enchantments like sharpness work.

**Comment by Dapro718** [comment]
Would teaspoon work?

**Comment by Heisenburger69** [comment]
PM implements Sharpness, not sure why this issue occurs

**Comment by iZeaoGamer** [comment]
Looting has been tested to work.
Not sure about sharpness though.

**Comment by iZeaoGamer** [comment]
Tested sharpness, and that seems to work for me.

**Comment by Heisenburger69** [comment]
Confirmed, issue only occurs for enchantments not registered by PM. Closing since it's not fixable within BurgerSpawners itself
