### ISSUE TITLE
Registering Mobs issue

### ISSUE THREAD

**Issue by thecouchyeti** [Heisenburger69/BurgerSpawners#34]
Okay, i wrote my issue on here rather than the plugin i meant to so edited it.

To note the issue im using this new boss plugin but with burgerspawners registering mobs which is what i want, the boss plugin doesnt register.

Unless you, Burger, have a boss plugin for sale that works with your spawner system

**Comment by Heisenburger69** [comment]
Please link the Boss plugin and mention the issue that occurs, in detail. If you have any error logs, send them too

**Comment by thecouchyeti** [comment]
The plugin: https://poggit.pmmp.io/ci/HmmHmmmm/BossPlugin/BossPlugin

The issue: when i have both your plugin and this one running there is a registery issue that causes mobs to vanish when they spawn. The only entities that spawn are cows sheep and non combat entited from the spawners.

There is no error code, its a registering issue and im not sure which one of you can change or fix it. 
When i disable registery in your plugin the boss plugin works but the spawners dont. When i do the opposite then yours works but the boss plugin doesnt.

**Comment by thecouchyeti** [comment]
And if theres a boss plugin you have Burger and if you are interested in selling a working copy so that i can continue to use trusted devs(as you muqs and others are), id dramatically appreciate it. 
If so i can give you my discord name or twitter

**Comment by Heisenburger69** [comment]
I'm presuming it's an issue with the MobStacker, try disabling the mobstacker in BurgerSpawners in the world where you want to spawn Bosses. As for a Boss Plugin, you can contact me on Discord at Heisenberg#9571
