### ISSUE TITLE
Xp to false doesn't work

### ISSUE THREAD

**Issue by Teunboeke** [Heisenburger69/BurgerSpawners#37]
So I just set xp to false bc its kinda laggy and if I spawn a zombie or somethings and I kill it I will still get xp

**Comment by Teunboeke** [comment]
?

**Comment by Heisenburger69** [comment]
Do you have any other plugins like PureEntitiesX or Teaspoon installed?

**Comment by Teunboeke** [comment]
I have teaspoon

**Comment by Heisenburger69** [comment]
The XP drops are due to Teaspoon, not due to BurgerSpawners. Disable Teaspoon and it should no longer occur

**Comment by Teunboeke** [comment]
Ok thx
