### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mikeygio10** [Heisenburger69/BurgerSpawners#4]
Before you break the mob spanner with a pick that it cant be breaken with a ui should pop up with it saying are you sure you want to destroy this spawner you cant get it back unless you use a silk touch or whatever

**Comment by Scottishman** [comment]
@Heisenburger69  I would like so suggest can You change the Mob Drop of the Panda from emeralds to Sugar Cane because Sugarcane fits more than Emeralds. also do you mind adding some more of the Village and Pillage mobs.

**Comment by provsalt** [comment]
> @Heisenburger69 I would like so suggest can You change the Mob Drop of the Panda from emeralds to Sugar Cane because Sugarcane fits more than Emeralds. also do you mind adding some more of the Village and Pillage mobs.

Kust wait for someone to pr custom drops lol

**Comment by Heisenburger69** [comment]
@mikeygio10 This might result in issues with permission plugins such as a Factions plugin. Players from other Factions could break your Faction's spawners using the UI

**Comment by Heisenburger69** [comment]
@Scottishman Custom Drops is already on the To-Do, you should be able to change the drops of every mob in a later release

**Comment by Scottishman** [comment]
@Heisenburger69  I know a way for you to add missing Items in pmmp but it would take you a long time to do but its possible. I can tell you what items all the mobs that dont have should.

**Comment by Scottishman** [comment]
dose this project have a discord

**Comment by Heisenburger69** [comment]
@Scottishman You can submit a PR registering the missing items. No discord for this, but my personal discord is Heisenberg#9571

**Comment by Scottishman** [comment]
@Heisenburger69  when is the 0.0.3 release
