### ISSUE TITLE
Iron Golem Bug

### ISSUE THREAD

**Issue by bulutsun** [Heisenburger69/BurgerSpawners#41]
I remove iron golem spawner with forms. But giving named with 'monster spawner' spawner.

**Comment by Heisenburger69** [comment]
Could you confirm if this bug occurs for other spawners with a space in their name? An example is Snow Golem Spawners

**Comment by bulutsun** [comment]
I think it's about space, as you said. I tried it in the Elder Guardian, Snow Golem and Cave Spider spawners. The same problem.

**Comment by bulutsun** [comment]
When can you fix it?

**Comment by Heisenburger69** [comment]
Fixed in latest build 👌
