### ISSUE TITLE
Not dropping any XP

### ISSUE THREAD

**Issue by youngjmc** [Heisenburger69/BurgerSpawners#43]
The mobs does not drop a single XP

**Comment by Heisenburger69** [comment]
Not implemented yet, if someone wants to PR, go for it

**Comment by youngjmc** [comment]
But I thought it says here

Configurable Options to modify XP drops, Spawner Rates, Mob and Spawner Stacking, Silk Touch and Entity Scale

**Comment by Heisenburger69** [comment]
XP Drops are only implemented for some mobs like Bees at the moment, those config options are to toggle that

**Comment by NormalOcean6686** [comment]
When will this be added?
