### ISSUE TITLE
This plugin keeps generating crash dumps for my server

### ISSUE THREAD

**Issue by JacobByrne68** [Heisenburger69/BurgerSpawners#45]
Hi, I have been using this plug-in for a while and it seems that I always have to remove it because whenever its on the server is causes a crash every 10 minutes, I'm not sure why and I thought that the recent update would fix it but if you have a fix for this please reply to this or message my discord at Jacob#6415.

**Comment by Heisenburger69** [comment]
You'll need to send the crash dump here for further support

**Comment by JacobByrne68** [comment]
Here is all the last crash dumps I got from burger Spawners before I
removed it.

**Comment by Heisenburger69** [comment]
Please send the crashdumps :p

**Comment by JacobByrne68** [comment]
I did send them to you :P but I'm using nukkitx now it doesn't crash the
server so yeah.

**Comment by JacobByrne68** [comment]
Yeah I might be switching to pocketkine again I'll send you the crash dumps
if I get any on the new server

**Comment by Heisenburger69** [comment]
Open a new issue whenever a crash arises
