### ISSUE TITLE
Addon?

### ISSUE THREAD

**Issue by DoorknobSoap** [Heisenburger69/BurgerSpawners#52]
Possible addon with CustomShopUI, AlexPads?

**Comment by Heisenburger69** [comment]
More info is needed, what would the addon even do?

**Comment by DoorknobSoap** [comment]
Oh sorry, just would create a value to getspawner and add to the shop list like {spawner_zombie} to fill in as an id in shop config. But i just read on your notes and are alreadry planning on having your own UI

**Comment by Heisenburger69** [comment]
This will be implemented in a later release within the plugin itself
