### ISSUE TITLE
suggestion / bug

### ISSUE THREAD

**Issue by jaylac2000** [Heisenburger69/BurgerSpawners#61]
add permission to pick it up with any pickaxe without silk touch

add option to change prefix - i know ive suggested this before but just bringing it up again

**Comment by jaylac2000** [comment]
also error, bees do not seem to clear with AutoClearLagg as well as my private /clearlagg command

**Comment by Heisenburger69** [comment]
Bees and Foxes entity ID's don't exist in PM, and hence they don't clear, nothing I can do about that
The prefix option will not be added
as for the last, create a separate issue with just the suggestion

**Comment by jaylac2000** [comment]
So you want me to create a plain suggestion for the prefix option being changeable ?
