### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by TetroYT** [Heisenburger69/BurgerSpawners#7]
add the option for autoinv (mob drops go straight to your inventory) you can disable or enable in config

this is mostly to avoid overloading the server etc but also a great way to stop players games lagging

**Comment by Heisenburger69** [comment]
Not sure if I want to add this to the plugin, but there's lots of external plugins on poggit that do this. For example: [AutoInv](https://poggit.pmmp.io/p/autoinv)

**Comment by TetroYT** [comment]
i tried that plugin just before i posted this and it doesnt work with mob drops unless i need to enable it some how
