### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by monsternecros** [Heisenburger69/BurgerSpawners#84]
*Add a mode that spawns 10 mobs if you have 10 mob spawners in 8 seconds and an example and add a way to kill them all at once and go to inventory And a Spawners Store Configurable Messages and Price Add a Delay to Add a Spawner Why is there a way to duplicate spawners ... 
, (Well I would appreciate it very much if you could put it on!)*

**Comment by jaylac2000** [comment]
1. there is a insta death option in config
2. there is no way to duplicate, this is an issue on your server
