### ISSUE TITLE
I cannot prevent individual mob types from being stacked

### ISSUE THREAD

**Issue by galaxytwenty** [Heisenburger69/BurgerSpawners#96]
Hey ich have a problem
in the **config** 

exempted-entities:
  - "chicken"
  - "exampleentity#2"

but the chicken **stacked**, i would like the chickens **not to be stacked**.
how can i make ?.

and other..
I cannot prevent the stacking in worlds either -> in the config:
spawner-stacking-disabled-worlds:
  - "Cityblock" <- My correct world folder name.

and i get an error when placing spawner 
i type /spanwer chicken 1 -> then i placed the Spanwer an Internal server Error
 [Server thread/CRITICAL]: Error: "Class 'Heisenburger69\BurgerSpawners\Events\SpawnerPlaceEvent' not found" (EXCEPTION) in "plugins/BurgerSpawners-master/src/Heisenburger69/BurgerSpawners/Items/SpawnerBlock" at line 90
[19:41:29] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/level/Level(1940): Heisenburger69\BurgerSpawners\Items\SpawnerBlock->place(object pocketmine\item\ItemBlock, object pocketmine\block\Air, object pocketmine\block\Bedrock, integer 1, object pocketmine\math\Vector3, object JackMD\NameSpaceRemover\CustomPlayer)

**PLS HELP**
**Best Regardz**

**Comment by galaxytwenty** [comment]
so far i haven't found a solution

**Comment by galaxytwenty** [comment]
# Entities listed here are exempted from stacking. The name of the entity must be the same as
# The name seen via /spawner list
exempted-entities:
  - "chicken"
  - "Chicken"

**Comment by galaxytwenty** [comment]
is this Project Alive ?

**Comment by Heisenburger69** [comment]
Fixed in dev build#95
